### ISSUE TITLE
Get register value from register id (python)

### ISSUE THREAD

**Issue by thebabush** [QBDI/QBDI#113]
Maybe I'm dumb, but is there any easy way to do it?

I get the register id from the operands analysis of an instruction, but I don't know what to do with it.
The C++ side seems to use the macro `#define QBDI_GPR_GET(state, i) (reinterpret_cast<QBDI::rword*>(state)[i])` to deal with it, but it's not available on the python side of course.

**Comment by nsurbay** [comment]
The next version of pyqbdi (with python 3) will add a **\_\_getitem\_\_** method on GPRState (https://github.com/QBDI/QBDI/blob/7e7ebcf9cecb0d544b911c544b4d53a6d383a3cd/tools/pyqbdi/binding/State_X86_64.cpp#L440)
