### ISSUE TITLE
Does qbdi support android arm or arm64?

### ISSUE THREAD

**Issue by hac425xxx** [QBDI/QBDI#115]
Does qbdi support android arm or arm64?

**Comment by hac425xxx** [comment]
does qbdi support jni function for android native library,  JNI function always need a vm argument for the first argument

**Comment by hac425xxx** [comment]
When the arm64 is supported, I want write a fuzzer for andorid arm64 based qbdi.

**Comment by hac425xxx** [comment]
I noticed that Android AArch64 seems work

```
https://twitter.com/rh0main/status/1168786403767083008
```
When is Android AArch64 version released?

**Comment by romainthomas** [comment]
Hello @hac425xxx 
We are still internally testing the ARM and AArch64 support but it's on a good track. Especially, it works with the JNI functions but we need to polish the integration along with x86 and x86_64.

**Comment by hac425xxx** [comment]
Thanks, waiting for aarch64 >.<
