### ISSUE TITLE
QBDI is too slow for fuzzing, something could impove the speed?

### ISSUE THREAD

**Issue by hac425xxx** [QBDI/QBDI#117]
The code of qbdi preload module is like below
```
unsigned int bbcount = 0;
unsigned long start = 0;
unsigned long end=0;

VMAction bb_cbk(VMInstanceRef vm, const VMState *vmState, GPRState *gprState, FPRState *fprState, void *data)
{
    if(gprState->rip >= start && gprState->rip<=end){
        bbcount += 1;
    }
    return QBDI_CONTINUE;
}

int dump_module_list(VMInstanceRef vm)
{
    size_t size = 0, i = 0;
    qbdi_MemoryMap *maps = qbdi_getCurrentProcessMaps(false, &size);
    for (i = 0; i < size; i++)
    {
        printf("%s (%c%c%c) ", maps[i].name,
               maps[i].permission & QBDI_PF_READ ? 'r' : '-',
               maps[i].permission & QBDI_PF_WRITE ? 'w' : '-',
               maps[i].permission & QBDI_PF_EXEC ? 'x' : '-');
        printf("(%#" PRIRWORD ", %#" PRIRWORD ")\n", maps[i].start, maps[i].end);

        if(maps[i].permission & QBDI_PF_EXEC && strstr(maps[i].name, "libredwg")!=NULL){
            start = maps[i].start;
            end = maps[i].end;
        }
    }
    qbdi_freeMemoryMapArray(maps, size);
    return 0;
}

int qbdipreload_on_start(void *main)
{
    return QBDIPRELOAD_NOT_HANDLED;
}

int qbdipreload_on_premain(void *gprCtx, void *fpuCtx)
{
    return QBDIPRELOAD_NOT_HANDLED;
}

int qbdipreload_on_main(int argc, char **argv)
{
    qbdi_addLogFilter("*", QBDI_DEBUG);
    return QBDIPRELOAD_NOT_HANDLED;
}

int qbdipreload_on_run(VMInstanceRef vm, rword start, rword stop)
{
    dump_module_list(vm);
    qbdi_addVMEventCB(vm, QBDI_BASIC_BLOCK_ENTRY, bb_cbk, NULL);

    qbdi_run(vm, start, stop);
    return QBDIPRELOAD_NO_ERROR;
}

int qbdipreload_on_exit(int status)
{
    printf("bbcount:%d\n", bbcount);
    return QBDIPRELOAD_NO_ERROR;
}

```

The exec time between dynamorio
```
$ time LD_BIND_NOW=1 LD_PRELOAD=/home/lsl/coding/QBDI/templates/qbdi_preload_template/build/libqbdi_tracer.so ~/workplace/libredwg-0.9.2400/examples/.libs/dwg2svg2 dwg_in/sample1000

bbcount:4844059

real	0m2.042s
user	0m2.024s
sys	0m0.016s

$ time ~/DynamoRIO-x86_64-Linux-7.0.17733-0/bin64/drrun -t drcov  --  ~/workplace/libredwg-0.9.2400/examples/.libs/dwg2svg2 dwg_in/sample1000

real	0m0.169s
user	0m0.156s
sys	0m0.012s

```

As you can see, the speed is too slow than dynamorio, something wrong?

**Comment by 0xAcid** [comment]
Hello,
QBDI has indeed some performance issue, however, that is something we partially overcome using a few tricks : for instance, a well-used fork-server can help (basic metrics are available slide 50 https://github.com/quarkslab/conf-presentations/blob/master/5th-France-Japan-CyberWorkshop/19-Kyoto-Fuzzing_Binaries_using_Dynamic_Instrumentation%20-%20HERNAULT%20Paul.pdf ).

Nevertheless, that is something we may work on in the near future. We already identified a few area of improvement, but that still requires some more testing and is not to be expected in the following months.

Also, feel free to contribute to the tool, as we would gladly welcome a Pull Request improving the performances of the tool.

**Comment by hac425xxx** [comment]
Thanks, I try add forkserver in qbdipreload_on_main, it seem not improve too much speed.
```
int qbdipreload_on_main(int argc, char **argv)
{
    qbdi_addLogFilter("*", QBDI_DEBUG);

    if(afl_area_ptr == 0){
        if(afl_setup()){
            afl_forkserver();
        }
    }

    return QBDIPRELOAD_NOT_HANDLED;
}
```

Maybe the location I start forkserver is false, where should I insert the forkserver  code?

**Comment by hac425xxx** [comment]
Is there documentation about the internal implementation of this tool? I am not too familiar with llvm， any suggestion for me to learn the code of QDBI?

**Comment by 0xAcid** [comment]
I would recommend reading the documentation (especially the "developper" part), which is a great starting point to get familiar with QBDI (and LLVM).

As for everything related to fuzzing, at the moment, we cannot disclose more than what has been presented in the slides I previously shared. We cannot provide support or assist you in this matter.

I close this issue as the speed improvement is already part of our roadmap.
