### ISSUE TITLE
Does qbdi_call support __stdcall、__thiscall or __fastcall?

### ISSUE THREAD

**Issue by hac425xxx** [QBDI/QBDI#119]
I find that `qbdi_call` don't provide arguments for the function  calling convention， Does qbdi_call support __stdcall、__thiscall or __fastcall? what's the default behavior?

**Comment by nezetic** [comment]
_qbdi_call_ is just a helper, implementing "default" calling conventions (__stdcall on x86 Windows).
We could provide a flag argument to customize the behaviour.

In meanwhile, it's possible to use _qbdi_run_ with a custom thread state to implement any kind of convention.
