### ISSUE TITLE
Does qbdi support thumb & thumb2 now

### ISSUE THREAD

**Issue by echo579** [QBDI/QBDI#122]
I'm trying to analysis JNI Library with qbdi tag v0.6.2. It seems v0.7.0 doesn't provide android_arm prebuilt and also I failed to compile it. I'm wondering how it works in JNI Library in this blog (https://blog.quarkslab.com/android-native-library-analysis-with-qbdi.html)

**Comment by romainthomas** [comment]
Hello @echo579 

The public version supports the ARM instruction set without Thumb/Thumb2 mode. The integration of Thumb/Thumb2 as well as AArch64 is in progress.
