### ISSUE TITLE
frida-qbdi.js - wrong version

### ISSUE THREAD

**Issue by Sh3idan** [QBDI/QBDI#133]
On the v0.7.1 branch, qbdi version has not been bump in the frida-qbdi.js: https://github.com/QBDI/QBDI/blob/v0.7.1/tools/frida-qbdi.js

The QBDI_PATCH variable must have the value '1':
```js
var QBDI_MAJOR = 0;
var QBDI_MINOR = 7;
var QBDI_PATCH = 1;
...
```

**Comment by nsurbay** [comment]
Thank you.

I create a post release `0.7.1.post1` with the corrected version. 
As the change is minor, we will not create packages for this version.

**Comment by Sh3idan** [comment]
Thanks :)
