### ISSUE TITLE
Question - qbdi-frida on Windows seems broken

### ISSUE THREAD

**Issue by Sh3idan** [QBDI/QBDI#134]
Hey,

I am trying to play with QBDI through Windows. As you say in the documentation (https://qbdi.readthedocs.io/en/stable/qbdi_preload.html), I use frida as loader like that :
```python
session = frida.attach(PROCESS_NAME)
script = session.create_script(source)
script.on("message", on_message)
script.load()
sys.stdin.read()
session.detach()
```

``source`` variable is the content of my js script. It is a part of the full Frida/QBDI example (https://qbdi.readthedocs.io/en/stable/frida_usage.html#complete-example):
```javascript
const qbdi = require("C:\\Program Files\\QBDI 0.7.1\\frida-qbdi");
qbdi.import();
```

When this script is loaded by Frida, I have the following error:
```python
{'type': 'error', 'description': "ReferenceError: identifier 'require' undefined", 'stack': "ReferenceError: identifier 'require' undefined\n    at [anon] (C:\\Users\\frida\\Buildbot\\frida-windows\\build\\frida-gum\\bindings\\gumjs\\duktape.c:83728)\n    at /script1.js:1", 'fileName': '/script1.js', 'lineNumber': 1, 'columnNumber': 1}
```

``require`` seems not supported by frida engine. What is wrong ?

frida version: 12.10.4
QBDI version: 0.7.1

Thanks.

**Comment by bla5r** [comment]
Hi there,

It seems you're trying to run your script without compiling it beforehand. Indeed, you need to include the file containing the QBDI bindings within your script. This step is mandatory and can be done by using [`frida-compile`](https://www.npmjs.com/package/frida-compile) utility. Further details are available at the [documentation page](https://qbdi.readthedocs.io/en/stable/frida_usage.html#scripts).

**Comment by Sh3idan** [comment]
Oh yes, thank you. Sorry for this issus.
