### ISSUE TITLE
Arm support

### ISSUE THREAD

**Issue by leiguo1029** [QBDI/QBDI#164]
Is there a plan to support arm/thumb in the future？I want to use it in android device，but it only support x86/x64

**Comment by romainthomas** [comment]
Hello @leiguo1029,

QBDI actually supports ARM/Thumb/Thumb2 and AArch64 but it's only available for internal use. If you (or your company) want 
to use it, please get in touch by mail.

Romain

**Comment by leiguo1029** [comment]
Yeah, I just need it，Can you share it to me，thanks..


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QBDI/QBDI"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月23日(星期二) 下午5:16
收件人:&nbsp;"QBDI/QBDI"<QBDI@noreply.github.com&gt;;
抄送:&nbsp;"年少輕狂"<1256748979@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [QBDI/QBDI] Arm support (#164)





 
Hello @leiguo1029,
 
QBDI actually supports ARM/Thumb/Thumb2 and AArch64 but it's only available for internal use. If you (or your company) want
 to use it, please get in touch by mail.
 
Romain

**Comment by lushann** [comment]
hi bro,did you get it already? I need it in android device too
