### ISSUE TITLE
How to get stable instruction address relative to image_base

### ISSUE THREAD

**Issue by anaivebird** [QBDI/QBDI#173]
Each time we run, image_base and all instruction's address changed.

So , what's the suggested way to hook a function inside program we analysis. How to get image_base so that we could substact it to get stable relative instruction address.

**Comment by nsurbay** [comment]
For C, C++ and PyQBDI API, we have some API to list the current process maps. For Frida, you may use [Process.findModuleByAddress(address)](https://frida.re/docs/javascript-api/#process-getmodulebyname), and get an offset relative the the begin of your module.

**Comment by anaivebird** [comment]
Thanks!
