### ISSUE TITLE
"Failed to load C:\Program Files\QBDI 0.8.0\lib\QBDI.dll (0)"

### ISSUE THREAD

**Issue by bluetickwarrior** [QBDI/QBDI#176]
Hello, i'm getting the error when trying to load the QBDI.dll.

The first two lines of my js script before running frida-compile:

**const qbdi = require('C:\\Program Files\\QBDI 0.8.0\\frida-qbdi.js');
qbdi.import();**

At first i thought it was an issue with permissions so i tried setting all file and folder permissions, and also tried copying the dll to Desktop (and editing frida-qbdi.js accordingly). However i still get the "failed to load" error.

Thanks in advance!

**Comment by nsurbay** [comment]
Hello,

Did you check the dependencies of QBDI.dll ? You may need to install the VC++ runtime to have VCRUNTIME140.dll and VCRUNTIME140_1.dll.

Best,

**Comment by nsurbay** [comment]
With no update, I will closed this issue. If you have any new issue, feel free to open an new issue.
