### ISSUE TITLE
don’t know where to put the llvm file

### ISSUE THREAD

**Issue by gtict112** [QBDI/QBDI#177]
When I compile qbdi on mac system, the following error is reported

 build % make -j4
make[2]: *** [CMakeFiles/missing-llvm] Error 1
make[1]: *** [CMakeFiles/missing-llvm.dir/all] Error 2
make: *** [all] Error 2

![image](https://user-images.githubusercontent.com/12459826/121183315-82cc2a80-c896-11eb-8d2a-0fd42d9fb781.png)

I don’t know where to put the llvm file

**Comment by gtict112** [comment]
I don’t know what "make llvm" means, I can compile a single llvm project

**Comment by nsurbay** [comment]
To compile QBDI from source, you need to run the followed command : 

```bash
git clone git@github.com:QBDI/QBDI.git
cd QBDI
mkdir build
cd build
../cmake/config/config-macOS-X86_64.sh
make llvm
../cmake/config/config-macOS-X86_64.sh
make -j4
```

We need a specific version of QBDI with specific option before compile QBDI. The command ``make llvm`` compile llvm with all the require option.

**Comment by gtict112** [comment]
Such an error, what library file am I missing. My computer is mac, Apple M1。
---------
make -j4                                                                                 
[  2%] Generating LLVM_static_test_depends.c
.....
[  9%] Building C object tools/QBDIPreload/CMakeFiles/QBDIPreload.dir/src/darwin_preload.c.o
/Users/wangzongbiao/git-source/QBDI/tools/QBDIPreload/src/darwin_preload.c:92:11: error: unknown type name 'x86_thread_state32_t'; did you mean 'arm_thread_state32_t'?
    const x86_thread_state32_t* ts = (x86_thread_state32_t*) gprCtx;
          ^~~~~~~~~~~~~~~~~~~~
          arm_thread_state32_t
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/mach/arm/thread_status.h:100:36: note: 'arm_thread_state32_t' declared here

**Comment by nsurbay** [comment]
The current version of QBDI doesn't support ARM or AARCH64. 

The compilation of QBDI hasn't been tested on a Apple M1. As Apple M1 has a ARM CPU and QBDI can only compile to X86 or X86_64, you may need to crosscompile it. At the moment, we only crosscompile for android with Android NDK. The project may need further development to compile from OSX ARM to OSX X86_64.

**Comment by gtict112** [comment]
thanks，Try another system, compile and try

**Comment by gtict112** [comment]
One more question, do I need the 'ndroid-ndk-r20' version to compile the ndk for Android arm? Can other versions work, 20b or others?

**Comment by nsurbay** [comment]
We don't think QBDI needs a specific version of Android NDK. The CI uses NDK r21d.

Please also note that the early support of ARM architecture is no longer maintained. If you want to test it, you can download the compiled package of [0.6.2](https://github.com/QBDI/QBDI/releases/tag/v0.6.2).

**Comment by gtict112** [comment]
'const qbdi = require('/usr/local/share/qbdi/frida-qbdi'); ' 
----
The download package does not contain the'frida-qbdi' file, only the'libQBDI.so' file, or do I have to compile the Android version by myself? I successfully compiled the linux x64 version but did not find the'frida-qdbi' file. Is it necessary to install'frida-compile' in the QDBI project for nmp?

**Comment by nsurbay** [comment]
The ticket derived from the original issue. I will ask you to create a separate issue for any new question and use the issue template to have all the relevant information about your environment, the commands you have run and the version of QBDI that you used.

The [documentation](https://qbdi.readthedocs.io/en/stable/get_started-frida.html) includes an example for using frida with QBDI and how to compile it. The documentation assumes that you install QBDI on your system. If it's not the case, you should update the ``require`` with the path to the ``frida-qbdi.js`` file. If the file isn't include in the package, it can be found in the directory ``tools`` of QBDI repository.
