### ISSUE TITLE
Documentation Page Not Found

### ISSUE THREAD

**Issue by robinkang63** [QBDI/QBDI#181]
Hi, Thanks for making this wonderful tool. I am going to setup QDBi server like frida-server on my android device but when I opened for documentation link, it's showing not found. can you please fix the link and if possible provide me a tutorial to set up on my android device

**Comment by nsurbay** [comment]
Hello,

Can you provide the page where you found the broken link ?
The whole documentation is available at [qbdi.readthedocs.io](https://qbdi.readthedocs.io/en/latest/index.html).  The revelant sections should be [Frida/QBDI Installation](https://qbdi.readthedocs.io/en/latest/installation_and_integration.html#frida-qbdi-installation) and [Getting Started - Frida/QBDI](https://qbdi.readthedocs.io/en/latest/get_started-frida.html).

**Comment by pistach3** [comment]
Hi,

The broken link is within your  `README.rst` file.
I've submitted a small patch here #182.

**Comment by nsurbay** [comment]
Thank for the merge request. Do not hesitate to open other issue or merge request if you found another broken link in the documentation.
