### ISSUE TITLE
Setup Example For Android x86/x86_64

### ISSUE THREAD

**Issue by pistach3** [QBDI/QBDI#183]
Hi,

I've read the blog posts you made about `QBDI` on Android. I find both the posts and the tool very cool :sunglasses: (I especially like [this post](https://blog.quarkslab.com/why-are-frida-and-qbdi-a-great-blend-on-android.html)).

However, I am confused as to how to make `QBDI` work nicely on Android.

I understand that the `ARM` part of `QBDI` is an internal tool from the different issues raised about `ARM` in the repo. However, I still would like to use `QBDI` with the Android emulators having an `x86` or `x86_64` architecture.

I am a bit lost as to what setup works with Android, and what setup doesn't.

*Would it be possible to have a description of a working Android setup from the QBDI team?*

For example, which `frida` version do you use with a specific `QBDI` version?
Which emulator specs do you have for `x86_64`/`x86`? (Android version, API number, build ID from the Android CI, ...)
Do you per chance use the `cuttlefish` emulator with `QBDI`?
Which `QBDI` version are you using at the time being for Android? (the `master` branch is behind the `dev-next` branch)

I also feel that the docs are missing examples for Android.

This information would help Android `QBDI` newcomers a lot.
I would be happy to help you test different configurations/examples for QBDI+Android on emulators.

Thank you.

**Comment by nsurbay** [comment]
Hello,

I may not be the best people to answer all your question as I not used a lot QBDI with Android. The documentation should be improved in many ways (example of usage for some feature, ... ).

> For example, which frida version do you use with a specific QBDI version?

`frida-qbdi.js` has been rewritten with the release 0.8.0 and need to have a support of ES2019. A version of frida greater or equals to 14.0 is needed with this release. I don't think `frida-qbdi.js` have other requirements.

>  Which emulator specs do you have for x86_64/x86? (Android version, API number, build ID from the Android CI, ...)

We have done a training last year with the emulator x86 (device 'pixel_xl', image 'system-images;android-28;default;x86'). 

> Do you per chance use the cuttlefish emulator with QBDI?

I don't think we have test with this emulator. If the emulator can execute frida and doen't have restriction with mmap and mprotect, I should work.

> Which QBDI version are you using at the time being for Android? (the master branch is behind the dev-next branch)

The `master` branch is the release branch. We merge 'dev-next' in 'master' at each release. Currently, the 'master' branch is the version 0.8.0 of QBDI. 
The `dev-next` branch has the new features and fixs for the next version. The branch should work but some features may be less tested.
