### ISSUE TITLE
TypeError QBDI+Frida on Android x86_64

### ISSUE THREAD

**Issue by pistach3** [QBDI/QBDI#184]
**Bug description**

Getting a `TypeError` from `frida-qbdi.js` on QBDI `0.8.0` on Android x64.

**Bug log**

```bash
TypeError: not a function
    at addInstrumentedModuleFromAddr (frida-qbdi.js:1025)
    at <anonymous> (index.js:15)
    at call (native)
    at o (node_modules/browser-pack/_prelude.js:1)
    at r (node_modules/browser-pack/_prelude.js:1)
    at <eval> (/compiled.js:1992)
```

**Version**
- OS: Android 11 - API 30
- Architecture: x64
- QBDI version 0.8.0
- Frida version 14.2.13
- Python version -

**Additional context**

I am using `frida` 14.2.13 on my host, and a matching 14.2.13 `frida-server` running on my emulators.

I installed `frida-compile` and `babelify` like so: `npm install frida-compile babelify`
I grabbed the `frida-qbdi.js` and `libQBDI.so` files from the Android 0.8.0 release on GitHub (`QBDI-0.8.0-android-X86_64.tar.gz`).

I compiled with (`index.js` is the file `FridaQBDI_sample.js` from the `qbdi_frida_template` directory):
```bash
./node_modules/.bin/frida-compile index.js -o compiled.js
```

I used the `SimpleXOR.c` example from the `qbdi_frida_template` folder, which I compiled for Android `x86_64` with `clang` from the Android NDK toolchain.

I launched `frida-server` on the device, pushed the 0.8.0 `libQBDI.so` and ran `frida` with:
```bash
frida -Uf /data/local/tmp/qbdi/SimpleXOR -l compiled.js
```

After that, I get a `TypeError` from `frida-qbdi.js`
```bash
TypeError: not a function
    at addInstrumentedModuleFromAddr (frida-qbdi.js:1025)
    at <anonymous> (index.js:15)
    at call (native)
    at o (node_modules/browser-pack/_prelude.js:1)
    at r (node_modules/browser-pack/_prelude.js:1)
    at <eval> (/compiled.js:1992)
```

Did I miss something, or am I using a bad `frida` version / `QBDI` version combination?

Thank you for your help.

**Comment by nsurbay** [comment]
Hello,

I don't think it's a problem with the version of frida. As some methods of QBDI are called before the error, `libQBDI.so` has been imported successfully in the process.

The method `addInstrumentedModuleFromAddr` is realy trivial and the most likely issue is that `addr` isn't a number, string or NativePointer.

Can you verify that frida find the symbol `Secret` and doesn't not return `null` before [FridaQBDI_sample.js#L15](https://github.com/QBDI/QBDI/blob/dev-next/templates/qbdi_frida_template/FridaQBDI_sample.js#L15)?
