### ISSUE TITLE
Android jniEnv->NewObject doesn't work

### ISSUE THREAD

**Issue by Alireza-Razavi** [QBDI/QBDI#203]
Hello!
QBDI doesn't work correctly with Android RunTime, after some debugging process i found that the jniEnv->NewObject not working.
I seems there are some problems while  **libart.so**  working with QBDI simulation.
Is there any solution ?

**Comment by nsurbay** [comment]
Hello,

We don't have issue with QBDI and libart.so at the moment. Can you specify how it's doesn't work ? Does the NewObject method return a null pointer / never return / crash ?

Can you add a callback to print all the executed instructions and verified that the code of `env->NewObject` isn't instrumented (the method may call malloc and should not be instrumented with QBDI.)

**Comment by Alireza-Razavi** [comment]
this is simple code can you test and get error on Android Studio:
```
jobject myFunc(JNIEnv* env, jclass obj , jint x){

    jclass clz = env->FindClass("com/myApp/ParseClass");
    jmethodID constructorID = env->GetMethodID(clz, "<init>", "(I)V");
    jint res2 = 2000 / x;
    jobject instance_from_ParseClass = env->NewObject(clz, constructorID, res2);

    return instance_from_ParseClass;
}

extern "C" JNIEXPORT jobject JNICALL
Java_com_myApp_MainActivity_parseMyInt(JNIEnv* env, jclass obj , jint x) {

    bool res;
    uint8_t *fakestack;
    QBDI::GPRState *state;

    QBDI::VM qvm{};
    state = qvm.getGPRState();
    assert(state != nullptr);
    res = QBDI::allocateVirtualStack(state, 0x40000, &fakestack); // StackSize changed to other values but no solved
    assert(res == true);
    res= qvm.addInstrumentedModuleFromAddr((rword)&myFunc);
    assert(res == true);

    rword retvalue;
    res = qvm.call(&retvalue, reinterpret_cast<QBDI::rword>(myFunc),{
            (rword)env, NULL , (rword)x
    });
    assert(res == true);
	
    alignedFree(fakestack);
	
    jobject mobj = nullptr;
	
    if (retvalue){
    jobject mobj = (jobject)retvalue;

}
    return mobj;
}

```

**Comment by Alireza-Razavi** [comment]
yes, i can add all library or some of them to Instruments but
how do this : verified that the code of env->NewObject isn't instrumented ??

**Comment by nsurbay** [comment]
I think the problem is ```    java.lang.StackOverflowError: stack size 8MB```.

When you run your function with `jobject real_output = jni_function(env, nullptr, jINPUT);`, the method will use the "main" stack. However, the instrumented code will use a dedicated stack (as QBDI uses the "main" stack to instrument the code). This stack is allocate with this line `allocateVirtualStack(state, STACK_SIZE, &fakestack);`. 

From this point, we can have two different causes:
1. The allocated size is too small to run `NewObject`. (`STACK_SIZE = 0x100000; // 1MB`). Can you try with a bigger stack (like `0x800000 \\ 8MB`)
2. The JVM (and the method `NewObject`) does some stack validation operation. For example, during the JVM initialization, the address and the size of the "main" stack has been detected and the method `NewObject` verify that the current stack pointer is within the detected stack. As the dedicated stack (allocated with mmap) is likely at a lower address, the JVM understands that the stack pointer has overflow.

If the cause is the second one, I don't have a magic solution. You may need to run QBDI on the allocated stack and the instrumented code on the "main" stack but you will need to use assembly code to change RSP register of the current method.

**Comment by Alireza-Razavi** [comment]
I have tested a lot of different values for the **stack size** but nothing will change.
Let me explain a bit easier:
1. I create JNIEnv and JVM using **libart.so** (They are defined globally and we have access to `env `and `jvm `from everywhere in code)
2. I call `myFunc `using QBDI VM like this:
```
qvm.call(&retvalue,  reinterpret_cast<QBDI::rword>(myFunc), {} );
```
3. This is `myFunc`:
```
    jclass clz = env->FindClass("com/myApp/ParseClass"); // <--- OK
    jmethodID constructorID = env->GetMethodID(clz, "<init>", "(I)V"); // <---- OK
    jint number = 2000;
    jobject myObj = env->NewObject(clz, constructorID, number); // <---- NewObject doesn't work and 'myObj' will be NULL
```
4. You can test this case yourself and you will see what will happen.
5. When i call `myFunc` without QBDI VM and outside of VM it works, but QBDI VM can't handle this case.

**Comment by Alireza-Razavi** [comment]
This is another log from above problem: 

```
art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: JNI NewStringUTF called with pending exception java.lang.StackOverflowError: stack size 8MB
art/runtime/java_vm_ext.cc:470]   at java.lang.String com.myApp.MainActivity.parseMyInt(java.lang.String) (MainActivity.java:-2)
art/runtime/java_vm_ext.cc:470]   at void com.myApp.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:30)
art/runtime/java_vm_ext.cc:470]   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6692)
art/runtime/java_vm_ext.cc:470]   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1118)
art/runtime/java_vm_ext.cc:470]   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2621)
art/runtime/java_vm_ext.cc:470]   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2729)
art/runtime/java_vm_ext.cc:470]   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
art/runtime/java_vm_ext.cc:470]   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1480)
art/runtime/java_vm_ext.cc:470]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
art/runtime/java_vm_ext.cc:470]   at void android.os.Looper.loop() (Looper.java:154)
art/runtime/java_vm_ext.cc:470]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6176)
art/runtime/java_vm_ext.cc:470]   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
art/runtime/java_vm_ext.cc:470]   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:891)
art/runtime/java_vm_ext.cc:470]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:781)
```

**Comment by Alireza-Razavi** [comment]
> I think the problem is ` java.lang.StackOverflowError: stack size 8MB`.
> 
> When you run your function with `jobject real_output = jni_function(env, nullptr, jINPUT);`, the method will use the "main" stack. However, the instrumented code will use a dedicated stack (as QBDI uses the "main" stack to instrument the code). This stack is allocated with this line `allocateVirtualStack(state, STACK_SIZE, &fakestack);`.
> 
> From this point, we can have two different causes:
> 
> 1. The allocated size is too small to run `NewObject`. (`STACK_SIZE = 0x100000; // 1MB`). Can you try with a bigger stack (like `0x800000 \\ 8MB`)
> 2. The JVM (and the method `NewObject`) does some stack validation operation. For example, during the JVM initialization, the address and the size of the "main" stack has been detected and the method `NewObject` verify that the current stack pointer is within the detected stack. As the dedicated stack (allocated with mmap) is likely at a lower address, the JVM understands that the stack pointer has overflowed.
> 
> If the cause is the second one, I don't have a magic solution. You may need to run QBDI on the allocated stack and the instrumented code on the "main" stack but you will need to use assembly code to change RSP register of the current method.

I worked on this for a long time and debug it but did not see any stack validation check routine in libart, please if have any info, share it to hook/patch/... plz. thank you.
