### ISSUE TITLE
Symbol lookup error in C++ example of QBDIPreload

### ISSUE THREAD

**Issue by derchr** [QBDI/QBDI#208]
**Bug description**
Hello,
I cannot run the QBDIPreload C++ example. When I try to run a simple hello world program together with the successfully compiled library, I get a symbol lookup error for the symbol `qbdi_removeInstrumentedModuleFromAddr`.
The C example works flawlessly on the other hand.

**Bug log**
```
LD_BIND_NOW=1 LD_PRELOAD=./libtracer_preload_cpp.so ./a.out                                                            ✘ INT
./a.out: symbol lookup error: ./libtracer_preload_cpp.so: undefined symbol: qbdi_removeInstrumentedModuleFromAddr
```

**Minimal code to reproduce the bug**
I just compiled the C++ example that comes with the project.

**Specific command to reproduce the bug**
Specific command used to compile and inject QBDI

**Version (please complete the following information):**
- OS: Arch Linux
- Architecture: X64
- QBDI version (returned by getVersion) and commit hash (if not a release version): 390f9870c969b03b376b51832769faafb40a1cd4 (current commit on dev-next branch)

**Additional context**
I tried also to build against the precompiled package of QBDI (version 0.8.0) for my distribution. This also did not work.

**Comment by nsurbay** [comment]
Hello,

Thanks for the issue.
The MR #209 fixs the problem for me and should be merge soon.

**Comment by derchr** [comment]
> Hello,
> 
> Thanks for the issue. The MR #209 fixs the problem for me and should be merge soon.

I just tested the MR and it fixes the issue for me. Thanks!
