### ISSUE TITLE
Trace function

### ISSUE THREAD

**Issue by thienha1** [QBDI/QBDI#231]
I dunno how to make script that can trace function like that:
![Opera Snapshot_2023-02-02_181218_www romainthomas fr](https://user-images.githubusercontent.com/18132856/216309513-b2ac0ae2-9877-45a1-a9da-6cbb09d757e7.png)
Can you help me make this one?

**Comment by nsurbay** [comment]
Hello,

As I'm not the author of https://www.romainthomas.fr/post/20-09-r2con-obfuscated-whitebox-part1/, you should contact the author directly if you want to have the corresponding source code.

To intercept syscall with QBDI, the method `addMnemonicCB("SYSCALL", ..)` (for X86_64) or `addMnemonicCB("SVC", ..)` (for AARCH64 or ARM)  can be used. During the associated callback, the syscall number and argument can be deduce from the GPRState.

**Comment by thienha1** [comment]
> Hello,
> 
> As I'm not the author of https://www.romainthomas.fr/post/20-09-r2con-obfuscated-whitebox-part1/, you should contact the author directly if you want to have the corresponding source code.
> 
> To intercept syscall with QBDI, the method `addMnemonicCB("SYSCALL", ..)` (for X86_64) or `addMnemonicCB("SVC", ..)` (for AARCH64 or ARM) can be used. During the associated callback, the syscall number and argument can be deduce from the GPRState.

Thank you, i'll find out

**Comment by nsurbay** [comment]
This seems to be solve. If you have any new issue, feel free to open an new issue.
