### ISSUE TITLE
what happen?

### ISSUE THREAD

**Issue by eachlove** [QBDI/QBDI#237]
<img width="495" alt="1688047986236" src="https://github.com/QBDI/QBDI/assets/49685186/eb6a4779-9dd7-4650-98a8-772e1ba9dcb2">

**Comment by nsurbay** [comment]
Please fill the [bug report template](https://github.com/QBDI/QBDI/blob/dev-next/.github/ISSUE_TEMPLATE/bug_report.md), I cannot help you with the current description.

You can inspire yourself of stackoverflow help center like [MRE](https://stackoverflow.com/help/minimal-reproducible-example).
