### ISSUE TITLE
How to use packed so files with frida/QBDI?

### ISSUE THREAD

**Issue by Rainker93** [QBDI/QBDI#238]
HI!!

If you remember, I really waited for QBDI to support ARM64.(I've sent you a mail before.)

Thank you so much for finally developing this.

First let me tell you my situation.

Purpose: Analyze so file on ARM64

Environment: Ubuntu 20.04
Mobile: Pixel

I saw an article analyzing packer on your blog.
(https://blog.quarkslab.com/qbdi-070.html)

I want to do analysis like this too.

First you get the function offset of init_array by lief.

![image](https://github.com/QBDI/QBDI/assets/115279571/25eefdfe-0cef-4dcf-83bd-ce930934b238)

Then, by adding 0x931 to the base address of the so file, the function address of init_array is stored in a variable called **ctr_addr**.

![image](https://github.com/QBDI/QBDI/assets/115279571/a573439c-5c0b-4fe5-99a7-0908c4ad2b1a)

But my target so file can't get the init_array offset address by lief.

Perhaps my target so file is packed, and it seems to be dynamically decrypted at run time.

![image](https://github.com/QBDI/QBDI/assets/115279571/1e26ef82-4b95-4916-adff-6a1b918b1b1f)

Also, the JNI_OnLoad function is not properly decompiled even when the packed SO file is opened.

![image](https://github.com/QBDI/QBDI/assets/115279571/f55c3cc2-c97a-425b-809e-3b88962b2fa0)

0x201DD8 "Decompilation stopped at DCB 0xFF, 0xFF, 0xFF, 0xFF.

Also, the same error occurs in "DCD 0xC4D583D8" of 0x201E04.

![image](https://github.com/QBDI/QBDI/assets/115279571/fc6a9510-79a2-488f-a3e8-5bb2a90b8568)

I think it is decoded in init_array before the JNI_OnLoad function is executed. Can you tell me how to analyze it using Frida/QBDI?

And finally, there is another problem.

Let me show you my code first:

``` 
(Setting QBDI)

Java.perform(function() 
{
    const libraryName = "libtest.so";
    waitForLibLoading(libraryName);
});


function waitForLibLoading(libraryName) 
{
    var isLibLoaded = false;

    Interceptor.attach(Module.findExportByName(null, "android_dlopen_ext"), 
    {
        onEnter: function (args) {
            var libraryPath = Memory.readCString(args[0]);
            if (libraryPath.includes(libraryName)) {
                console.log("[+] Loading library " + libraryPath + "...");
                isLibLoaded = true;
            }
        },
        onLeave: function (args) {
            if (isLibLoaded) 
            {

                processJniOnLoad(libraryName);
                var module = Process.findModuleByName(libraryName);

                console.log("[*] Base: " + module.base);
                isLibLoaded = false;
            }
        }
    });
}

function processJniOnLoad(libraryName) 
{
    const funcSym = "JNI_OnLoad";
    const funcPtr = Module.findExportByName(libraryName, funcSym);

    console.log("[+] Replacing " + funcSym + "() @ " + funcPtr + "...");
    
    // jint JNI_OnLoad(JavaVM *vm, void *reserved);
    
    Interceptor.replace(funcPtr, new NativeCallback(function (load_vm, load_reserved) 
    {
        const vm = load_vm;
        const reserved = load_reserved;
        console.log("[+] " + funcSym + "(" + vm + ", " + reserved + ") called");
        Interceptor.revert(funcPtr); // revert to the genuine implementation
        Interceptor.flush(); // ensure changes have been actually committed
        var retVal = qbdiExec(this.context, funcPtr, funcSym, [vm, reserved], true);
        processJniOnLoad(libraryName, funcSym); // replace the implementation again for a potential call later on
        return retVal;
    }, "long", ["pointer", "pointer"]));

}

function qbdiExec(ctx, funcPtr, funcSym, args, postSync) 
{
    var vm = new VM(); // create a QBDI VM
    var state = vm.getGPRState();

    state.synchronizeContext(ctx, SyncDirection.FRIDA_TO_QBDI); // set up QBDI's context
    var stack = vm.allocateVirtualStack(state, 0x10000); // allocate a virtual stack
    

    vm.addInstrumentedModuleFromAddr(funcPtr);

    var icbk = vm.newInstCallback(function (vm, gpr, fpr, data) 
    {
        var inst = vm.getInstAnalysis();
        console.log("0x" + inst.address.toString(16) + " " + inst.disassembly);
        return VMAction.CONTINUE;
    });

    var iid = vm.addCodeCB(InstPosition.PREINST, icbk); // register pre-instruction callback

    var vcbk = vm.newVMCallback(function (vm, evt, gpr, fpr, data) 
    {
        const module = Process.getModuleByAddress(evt.basicBlockStart);
        const offset = ptr(evt.basicBlockStart - module.base);
        if (evt.event & VMEvent.EXEC_TRANSFER_CALL) {
            console.warn(" -> transfer call to 0x" + evt.basicBlockStart.toString(16) + " (" + module.name + "@" + offset + ")");
        }
        if (evt.event & VMEvent.EXEC_TRANSFER_RETURN) {
            console.warn(" <- transfer return from 0x" + evt.basicBlockStart.toString(16) + " (" + module.name + "@" + offset + ")");
        }
        return VMAction.CONTINUE;
    });
    var vid = vm.addVMEventCB(VMEvent.EXEC_TRANSFER_CALL, vcbk); // register transfer callback

    var vid2 = vm.addVMEventCB(VMEvent.EXEC_TRANSFER_RETURN, vcbk); // register return callback

    const javavm = ptr(args[0]);
    const reserved = ptr(args[1]);

    console.log("[+] Executing " + funcSym + "(" + javavm + ", " + reserved + ") through QBDI...");
    vm.call(funcPtr, [javavm, reserved]);
    var retVal = state.getRegister(); // x86 so return value is stored on $eax
    console.log("[+] " + funcSym + "() returned " + retVal);
    if (postSync) {
        state.synchronizeContext(ctx, SyncDirection.QBDI_TO_FRIDA);
    }
    return retVal;
}
````

 I tried using the JNI_OnLoad function as QBDI, but this error occurs at the end.

![image](https://github.com/QBDI/QBDI/assets/115279571/e1e9721e-14ca-4698-8f64-6d44565ab496)

I am wondering how to solve this error.

Finally, it is difficult to use frida/QBDI because there are not many detailed examples and documents about frida/QBDI, but thank you for developing it to support ARM64.

**Comment by nsurbay** [comment]
Hello,
Thank for using QBDI.

For your problem with ``init_array``, it more an issue with LIEF or ELF file than QBDI. In an ELF file, all contructors must be declared in the ``init_array``, otherwith, there are not executing. The blog post also uses ``readelf -d`` to verify the dynamic section of your ELF binary. If ``readelf`` returns a different output than LIEF, they may be an issue in LIEF itself. Otherwise, either they are no constructors, or the library use a obfuscation method that I don't know (maybe using the relocation to patch ``init_array``). I will not be able to help you more on this issue without the library.

For your second issue, you may want to read the documentation of [getRegister](https://qbdi.readthedocs.io/en/stable/api_js.html#GPRState.getRegister). This method expect an argument to select which register to get. If the return value is within x0, you should pass ``0`` or ``"X0"``.

Also, your function ``qbdiExec`` allocates a new stack for QBDI, but doesn't clear it when it returns. You should to add a ``alignedFree(stack)`` before ``return retVal``. I'm not sure that ``SyncDirection.QBDI_TO_FRIDA`` is implemented, but as frida will set the return value in the register, all other registers keep their value before the call. This should not have an impact on the execution.

**Comment by Rainker93** [comment]
First of all thanks for answering my question!!

As for the second answer, I'll try to comment again.

Finally, thank you again.

**Comment by nsurbay** [comment]
This issue seems to be solve. If you have any new issue, feel free to open an new issue.
