### ISSUE TITLE
frida qbdi  Error: access violation accessing 0x0

### ISSUE THREAD

**Issue by imethod** [QBDI/QBDI#240]
**Bug description**
I often encounter this use of qbdi when I wonder how it happens and what are the ways to avoid it
![image](https://github.com/QBDI/QBDI/assets/109936536/1524276f-a23e-49c5-8f2e-c03d51bc1570)

**Bug log**

Error: access violation accessing 0x0
    at run (trace/qbdi/arm/frida-qbdi.js:1192)
    at Qbdi (trace/qbdi/qbdi.ts:42)
    at <anonymous> (agent/index.ts:26)
Process terminated

**Comment by nsurbay** [comment]
Hello,

I can't help you with the current description. Your log include a `qbdi.ts`, but we don't have any tutorial that use typescript. Moreover, the `run` method in the current version of `frida-qbdi.js` isn't at the line 1192.

Can you please provide scripts, binary target, software version, changed files and any others instructions necessary to reproduce the issue on my side ?

**Comment by imethod** [comment]
The sample is too big
Qbdi.ts is a ts script that I wrote to encapsulate frida and qbdi
I changed the type of frida-qbdi.js because the parameter type was marked in frida-qbdi.js so the ts compilation failed

And I found that ynchronizeContext was not implemented in the documentation, so I made some changes. run method in the current version of frida-qbdi.js isn't at the line 1192.
![image](https://github.com/QBDI/QBDI/assets/109936536/a2df1cc0-04de-4165-a41e-4ad6a7f5b93b)


[qbdi.txt](https://github.com/QBDI/QBDI/files/12193775/qbdi.txt)

**Comment by nsurbay** [comment]
Why do you change ``synchronizeContext`` ? With the current version, three registers isn't synchronized : LR, PC and CPSR. While the synchronization of PC is not needed (as you specify it when calling ``call``) and the synchronisation of CPSR should have little impact if PC is the begin of the function, I don't understand why you don't synchronized LR.

As you don't synchronize LR, the LR uses by QBDI has a different value of the LR in the frida context. When you call the method ``run`` ( [here](https://github.com/imethod/fridaqbdi/blob/main/trace/qbdi/qbdi.ts#L42) ), you specify the later one, while the QBDI's LR is more that likely equals to 0. When QBDI finish to execute your function, it jump to QBDI LR (with the null address) and fail to detect that it should stop, because you specify another address to stop the execution. Therefore, QBDI try to access to the address 0.

**Comment by imethod** [comment]
> 你为什么改变`synchronizeContext`？在当前版本中，三个寄存器不同步：LR、PC 和 CPSR。虽然不需要 PC 的同步（正如您在调用时指定的那样`run`），并且如果 PC 是函数的开头，则 CPSR 的同步应该影响不大，但我不明白为什么您不同步 LR。
> 
> 由于您不同步 LR，QBDI 使用的 LR 与 frida 上下文中的 LR 具有不同的值。当您调用该方法`run`（[此处](https://github.com/imethod/fridaqbdi/blob/main/trace/qbdi/qbdi.ts#L42)）时，您指定了后一个，而 QBDI 的 LR 很可能等于 0。当 QBDI 完成执行您的函数时，它会跳转到 QBDI LR（具有空地址）并且无法检测到它应该停止，因为您指定了另一个地址来停止执行。因此，QBDI尝试访问地址0。

thanks 
This issue has been resolved and qbdi is no longer reporting errors.
mov pc,lr  lr Now it's a normal value.
But I found that qbdi lost control of the program after that
Instead of stopping at the address I gave him, he lost control after modifying the pc
![image](https://github.com/QBDI/QBDI/assets/109936536/b0fd20e7-48cc-48bc-99d4-6e6e6586a39d)

**Comment by imethod** [comment]
> Why do you change `synchronizeContext` ? With the current version, three registers isn't synchronized : LR, PC and CPSR. While the synchronization of PC is not needed (as you specify it when calling `run`) and the synchronisation of CPSR should have little impact if PC is the begin of the function, I don't understand why you don't synchronized LR.
> 
> As you don't synchronize LR, the LR uses by QBDI has a different value of the LR in the frida context. When you call the method `run` ( [here](https://github.com/imethod/fridaqbdi/blob/main/trace/qbdi/qbdi.ts#L42) ), you specify the later one, while the QBDI's LR is more that likely equals to 0. When QBDI finish to execute your function, it jump to QBDI LR (with the null address) and fail to detect that it should stop, because you specify another address to stop the execution. Therefore, QBDI try to access to the address 0.

thanks (●'◡'●)
This issue has been resolved and qbdi is no longer reporting errors.
mov pc,lr  lr Now it's a normal value.
But I found that qbdi lost control of the program after that
Instead of stopping at the address I gave him, he lost control after modifying the pc
![image](https://github.com/QBDI/QBDI/assets/109936536/b0fd20e7-48cc-48bc-99d4-6e6e6586a39d)

**Comment by nsurbay** [comment]
What do you means by 'lost control' ? Can you shared your new script ?

The instruction ``mov pc, lr`` is usually used to return from a function. If the new address is the stop address you pass to the ``run`` method, QBDI will stop the native instrumentation and the control will be given back to your frida script. You must then copied any return value to the frida context, clean the QBDI VM and his stack (to avoid memory leak) and continue the instrumentation of java code with frida. It's also your frida script that must detect, catch and transfert future native execution to QBDI when it's revelant.

**Comment by imethod** [comment]
> What do you means by 'lost control' ? Can you shared your new script ?
> 
> The instruction `mov pc, lr` is usually used to return from a function. If the new address is the stop address you pass to the `run` method, QBDI will stop the native instrumentation and the control will be given back to your frida script. You must then copied any return value to the frida context, clean the QBDI VM and his stack (to avoid memory leak) and continue the instrumentation of java code with frida. It's also your frida script that must detect, catch and transfert future native execution to QBDI when it's revelant.

I just set the break in the synchronizeContext to continue.
I set everything except the fp register.
![image](https://github.com/QBDI/QBDI/assets/109936536/aabf6076-117c-44ee-8701-542980d361e7)

"lost control" 
This ret should be the return of the call to the subfunction.
However, qbdi does not print the inst of 0xBF697018 
![image](https://github.com/QBDI/QBDI/assets/109936536/1c35a66d-b30e-4a7c-8df5-be2729db2b7b)
![image](https://github.com/QBDI/QBDI/assets/109936536/8ee9b07b-19c9-4967-a173-48bcdc7abbc7)
log proves that the return value of lr is correct ()
![image](https://github.com/QBDI/QBDI/assets/109936536/2936818b-65dc-464a-9244-5bdcfa2cb673)

**Comment by imethod** [comment]
> > What do you means by 'lost control' ? Can you shared your new script ?
> > The instruction `mov pc, lr` is usually used to return from a function. If the new address is the stop address you pass to the `run` method, QBDI will stop the native instrumentation and the control will be given back to your frida script. You must then copied any return value to the frida context, clean the QBDI VM and his stack (to avoid memory leak) and continue the instrumentation of java code with frida. It's also your frida script that must detect, catch and transfert future native execution to QBDI when it's revelant.
> 
> I just set the break in the synchronizeContext to continue. I set everything except the fp register. ![image](https://user-images.githubusercontent.com/109936536/257181548-aabf6076-117c-44ee-8701-542980d361e7.png)
> 
> "lost control" This ret should be the return of the call to the subfunction. However, qbdi does not print the inst of 0xBF697018 ![image](https://user-images.githubusercontent.com/109936536/257183766-1c35a66d-b30e-4a7c-8df5-be2729db2b7b.png) ![image](https://user-images.githubusercontent.com/109936536/257183861-8ee9b07b-19c9-4967-a173-48bcdc7abbc7.png) log proves that the return value of lr is correct () ![image](https://user-images.githubusercontent.com/109936536/257184630-2936818b-65dc-464a-9244-5bdcfa2cb673.png) So I thought qbdi lost control of the program. The pc changes to 0xBF697018 context does not properly recover, program crashes.
> 
> https://github.com/imethod/fridaqbdi

Additional evidence
![image](https://github.com/QBDI/QBDI/assets/109936536/a4918395-4a9b-4ccc-94d7-8999a10e1cd8)

**Comment by nsurbay** [comment]
I think I missread your code Friday (and read LR instead of FP). They were 5 registers that was not synchronized : FP, SP, LR, PC and CSPR. Now, only FP isn't synchronized. Do you have a specific reason to not synchronized it ? Does it have a different name in frida context and need a fix ?

Now that the value of LR is synchronized, the ``mov pc, lr`` will set the original synchronized frida value of LR in PC. But, you specify that QBDI must stop his execution when ``context.lr.toInt32())`` is reach (as the second argument of the method ``run``). So QBDI stops the execution as requested.

**Comment by imethod** [comment]
> 
frida context no fp
![image](https://github.com/QBDI/QBDI/assets/109936536/05ace33e-9960-4de0-b853-e9eeb2056a8a)
![image](https://github.com/QBDI/QBDI/assets/109936536/9732d9ef-3d00-42e3-899b-16b82c236ff8)
![image](https://github.com/QBDI/QBDI/assets/109936536/9a8a85c4-ae1a-4157-96b5-2f6da52bd869)

Note that the address of bl is not the same function. I trace the address is 0xBF696F50 whereas sub_BF696F50 () will call sub_BF696814 () which is not the correct flow
![image](https://github.com/QBDI/QBDI/assets/109936536/546abbc6-6071-4294-b52d-e4deca29b642)

**Comment by nsurbay** [comment]
``FP`` seems to be an alias for ``R11`` register. A proper fix should be to change the line [347](https://github.com/imethod/fridaqbdi/blob/main/trace/qbdi/arm/frida-qbdi.js#L347) by:
```js
var GPR_NAMES_ = ["R0","R1","R2","R3","R4","R5","R6","R7","R8","R9","R10","R11","R12","SP","LR","PC","CPSR"];
```

As I don't have access to your library, I can't help you effectively with this issue. 

To verify my point, you can add a print around ``run`` :
```js
console.log(" vm.run start : pc:" + context.pc.toInt32() + ", lr:" + context.lr.toInt32());
vm.run(context.pc.toInt32(), context.lr.toInt32())
state = vm.getGPRState();
console.log(" vm.run stop : pc:" + state.getRegister("pc") + ", lr:" + state.getRegister("lr"));
```
If PC when ``run`` returns has the same value as LR before ``run``, it just that your stop point has been reach. If you think this not when you expect the method to return, you may instrument recursive code. In this case, you may try somethings like (which is similar of what the ``call`` method do internally) :

```js
state.setRegister("lr", 0x42)
vm.run(context.pc.toInt32(), 0x42)
```

**Comment by nsurbay** [comment]
It seems that your patch of ``GPR_NAMES_`` isn't the one that I give you. You add the register "R11" but don't remove the register "FP". This cause the index of others registers to be shift by one [here](https://github.com/imethod/fridaqbdi/blob/main/trace/qbdi/arm/frida-qbdi.js#L849), which cause the value of SP register to be put in LR during the synchronization of register between frida and QBDI. 
I push the patch https://github.com/QBDI/QBDI/commit/99e7083d510443709029ff3efca627d18ef3b9b2 int the dev-next branch, as this impact the synchronization of the register ``R12``.

Once you fix the patch of ``GPR_NAMES_``, we should have the same result as when QBDI "lost control" of the execution.

**Comment by imethod** [comment]
You're right.  I thought GPR_NAMES_ was using strings to locate registers, but some other function used its index
![image](https://github.com/QBDI/QBDI/assets/109936536/27b01231-8f6d-477f-9a0a-75d7381b5053)
QBDI "lost control" of the execution.

**Comment by nsurbay** [comment]
I no longer see any potential error in your code, so I will need to take a deeper look to QBDI.
Can you confirm me that the instruction ``mov	pc, lr`` has the followed assembly : ``[0x0e,0xf0,0xa0,0xe1]`` ? Can you also confirm that the mnemonic of the instruction (with ``inst.mnemonic`` [doc](https://qbdi.readthedocs.io/en/stable/api_js.html#InstAnalysis.mnemonic)) is ``MOVPCLR`` or ``MOVr``.

I just try to check with LLVM tools, but the instruction give two differents opcode, depending on how we provide it:
```
$ llvm_mc3_arm '[0x0e,0xf0,0xa0,0xe1]' 
	.text
	mov	pc, lr                          @ encoding: [0x0e,0xf0,0xa0,0xe1]
                                        @ <MCInst #896 MOVPCLR
                                        @  <MCOperand Imm:14>
                                        @  <MCOperand Reg:0>>

$ llvm_mc2_arm 'mov     pc, lr'                 
	.text
<stdin>:1:1: note: parsed instruction: ['mov', <ccout noreg>, <ARMCC::al>, <register pc>, <register lr>]
mov     pc, lr
^
	mov	pc, lr                          @ encoding: [0x0e,0xf0,0xa0,0xe1]
                                        @ <MCInst #900 MOVr
                                        @  <MCOperand Reg:14>
                                        @  <MCOperand Reg:13>
                                        @  <MCOperand Imm:14>
                                        @  <MCOperand Reg:0>
                                        @  <MCOperand Reg:0>>
```

I think that QBDI has the support for ``MOVr`` but not for ``MOVPCLR``.

**Comment by nsurbay** [comment]
I push a commit to #241 and ask the CI to generate the new android package [here](https://github.com/QBDI/QBDI/actions/runs/5729656003). Can you download the ARM android package and change libQBDI.so with the patched one ?

**Comment by imethod** [comment]
> 我将提交到[#241，并要求 CI](https://github.com/QBDI/QBDI/pull/241)[生成](https://github.com/QBDI/QBDI/actions/runs/5729656003)新的 android 包。您可以下载 ARM android 包并用打过的包更改 libQBDI.so 吗？
Yes, this is I used the screenshot of qbdi.so you provided, the problem is solved run successfully returned

![image](https://github.com/QBDI/QBDI/assets/109936536/0d54e5d4-dd57-4641-95db-3ed9c0169e78)
