### ISSUE TITLE
Why can't I find the libQBDI.so file

### ISSUE THREAD

**Issue by gtict112** [QBDI/QBDI#244]
Now I'm doing some work with frida+qbdi, I wrote a js file, but I can't find libQBDI.so, the file has been put into the phone directory /data/local/tmp;
My mobile phone is customized. I named it myself instead of using su to elevate my rights. Is it related to this?

--------------------------
21992351-391a-4d54-ab9e-46adadda99d7  estrace             re.frida.server   trace.log
android_x64_server                    fr16.0.1.64  libQBDI.so  stackplz          xx
dalvik-cache                          frstr        perfd       stackplz_tmp.log
flame:/data/local/tmp #

-------------------log
Spawning `com.xxx.xxxxxxxxxxxxxxxx...                                      
libQBDI.so library not found...
Spawned `com.tencent.mobileqq`. Resuming main thread!                   
Error: libQBDI.so library not found...
    at load (QBDI/usr/local/share/qbdiAARCH64/frida-qbdi.js:89)
    at load (QBDI/usr/local/share/qbdiAARCH64/frida-qbdi.js:145)
    at <anonymous> (QBDI/usr/local/share/qbdiAARCH64/frida-qbdi.js:195)
    at call (native)
    at o (node_modules/browser-pack/_prelude.js:1)
    at <anonymous> (node_modules/browser-pack/_prelude.js:1)
    at <anonymous> (utils/FCAnd.ts:13)
    at call (native)

**Comment by gtict112** [comment]
t’s ok to change the name of the right to su

**Comment by nsurbay** [comment]
Hello,

To verify if the file exist, the binding try to open the library file with ``File(cpath, "rb");`` [here](https://github.com/QBDI/QBDI/blob/dev-next/tools/frida-qbdi.js#L59).

I recommand to run a single script to verify that frida is able to read the file.
```JS
Java.perform(function() {
    var cpath = '/data/local/tmp/libQBDI.so';
    try {
        var fp = new File(cpath, "rb");
        fp.close();
        found = true;
        console.log('Found ' + cpath);
    } catch(e) {
        console.error(cpath + ' not found...');
    }
}
```

**Comment by nsurbay** [comment]
With no update, I will closed this issue. If you have any new issue, feel free to open an new issue.
