### ISSUE TITLE
QBDI crash when meeting clone and execve

### ISSUE THREAD

**Issue by 18712886438** [QBDI/QBDI#249]
**Bug description**

"Hello, I am currently using QBDI to trace Android native code. I have encountered a method that uses clone and then executes execve in the child process. It is expected that execve should be executed in the child process rather than the parent process. However, due to clone causing both processes to share memory, the state within QBDI for the parent process also gets modified by the child process, which then leads to the execution of execve and consequently causes the program to crash. Currently, I have tried saving GPRState/FPRState before clone, and then restoring the previously saved GPRState/FPRState before the erroneous execution of execve in the parent process. But there is a warning: [warning] (execute) ExecBlock.cpp:219 Callback returned CONTINUE but change PC: Ignore new value. What should I do now to avoid the crash issue?"

**Bug log**
 W  [warning] (execute) ExecBlock.cpp:219 Callback returned CONTINUE but change PC: Ignore new value

**Minimal code to reproduce the bug**
```
std::map<pid_t, QBDI::GPRState *> qbdi_gprstate_map;
std::map<pid_t, QBDI::FPRState *> qbdi_fprstate_map;

void save_vm_ctx(QBDI::VM *vm) {
    auto pid = getpid();
    auto gprState = vm->getGPRState();
    auto fprState = vm->getFPRState();
    qbdi_gprstate_map.insert(std::make_pair(pid, gprState));
    qbdi_fprstate_map.insert(std::make_pair(pid, fprState));
}

void restore_qbdi_ctx(QBDI::VM *vm) {
    auto pid = getpid();

    if (qbdi_fprstate_map.find(pid) != qbdi_fprstate_map.end()
    && qbdi_gprstate_map.find(pid) != qbdi_gprstate_map.end()) {
        auto gprState = qbdi_gprstate_map[pid];
        auto fprState = qbdi_fprstate_map[pid];
        vm->setGPRState(gprState);
        vm->setFPRState(fprState);
        qbdi_fprstate_map.erase(pid);
        qbdi_gprstate_map.erase(pid);
    }
}
QBDI::VMAction svc_callback_pre(QBDI::VM *vm, QBDI::GPRState *gprState,
                                QBDI::FPRState *fprState, void *data) {
    
    const QBDI::InstAnalysis *instAnalysis = vm->getInstAnalysis(QBDI::ANALYSIS_INSTRUCTION | QBDI::ANALYSIS_DISASSEMBLY);

    if (memcmp(instAnalysis->disassembly, "\tsvc\t#0", sizeof("\tsvc\t#0")) != 0) {
        return QBDI::VMAction::CONTINUE;
    }
    // Get the value of x8 register
    QBDI::rword x8_value = QBDI_GPR_GET(gprState, 8);
    if (x8_value == __NR_clone) {
        save_vm_ctx(vm);
    }
    if (x8_value == __NR_execve || x8_value == __NR_exit) {
        restore_qbdi_ctx(vm);
    }

    return QBDI::VMAction::CONTINUE;
}
```

**Specific command to reproduce the bug**

**Version (please complete the following information):**
- OS: [Android]
- Architecture: [aarch64]

**Comment by nsurbay** [comment]
Hello.

QBDI doesn't support the shared of a same VM instance between two process/thread.
For this clone syscall, you should take care of the first argument (the function pointer). If QBDI work well, this pointer should be a known address of your program and not a address of the page mapped by QBDI to instrument code.

After the clone syscall, the parent should continue to be instrumented by QBDI (with the address after the svc), while the child should execute natively the first argument. If this isn't the observed behavior, can you provide a trace of the execution around the clone syscall ?

Also note that your method ``save_vm_ctx`` doen't perform what you may expect. ``getFPRState`` returns pointer to the internal state of QBDI, state that may be change after the return of the callback. You should perform a proper copy of the state.

For the warning ``Callback returned CONTINUE but change PC``, it relatives to your method ``restore_qbdi_ctx`` and the return value ``CONTINUE``. When you change the process counter in a callback (by assigned a new ``GPRState`` with ``setGPRState`` or by using ``gprState->pc``), you must return [BREAK_TO_VM](https://qbdi.readthedocs.io/en/stable/api_cpp.html#_CPPv4N4QBDI8VMAction11BREAK_TO_VME). This cause QBDI to stop the execution of the current instruction (and any others callback associate with the current instruction) and begin the execution (and the associated callback) of the new instruction pointer. With the current implementation, QBDI will continue to execute the current instruction, but all the other register will be changed.

**Comment by 18712886438** [comment]
> Hello.
> 
> QBDI doesn't support the shared of a same VM instance between two process/thread. For this clone syscall, you should take care of the first argument (the function pointer). If QBDI work well, this pointer should be a known address of your program and not a address of the page mapped by QBDI to instrument code.
> 
> After the clone syscall, the parent should continue to be instrumented by QBDI (with the address after the svc), while the child should execute natively the first argument. If this isn't the observed behavior, can you provide a trace of the execution around the clone syscall ?
> 
> Also note that your method `save_vm_ctx` doen't perform what you may expect. `getFPRState` returns pointer to the internal state of QBDI, state that may be change after the return of the callback. You should perform a proper copy of the state.
> 
> For the warning `Callback returned CONTINUE but change PC`, it relatives to your method `restore_qbdi_ctx` and the return value `CONTINUE`. When you change the process counter in a callback (by assigned a new `GPRState` with `setGPRState` or by using `gprState->pc`), you must return [BREAK_TO_VM](https://qbdi.readthedocs.io/en/stable/api_cpp.html#_CPPv4N4QBDI8VMAction11BREAK_TO_VME). This cause QBDI to stop the execution of the current instruction (and any others callback associate with the current instruction) and begin the execution (and the associated callback) of the new instruction pointer. With the current implementation, QBDI will continue to execute the current instruction, but all the other register will be changed.

Thx for reply! According to the trace log after the clone syscall, the parent continued to be instrumented by QBDI .
And I will try to modify the code as you said. Thanks again.
