### ISSUE TITLE
how to user QBDI don't  trace into bl function in android.

### ISSUE THREAD

**Issue by yujack008** [QBDI/QBDI#257]
i cant not found any example about it.

**Comment by nsurbay** [comment]
Can you be more precise on your setup and what you want to do ?

**Comment by yujack008** [comment]
> Can you be more precise on your setup and what you want to do ?

when execute the "bl xxxx" instruction, i don't want trace into all function.

**Comment by nsurbay** [comment]
We don't have an API that allow to easily skip the target of a call. However, you may achieved what you want with the [Instrumentation Ranges](https://qbdi.readthedocs.io/en/stable/api_description.html#instrumentation-ranges). This mechanism is usually used to avoid tracing call of another library (like libc). Although I do not recommend it, it is possible to use this mechanism to exclude the first instructions of a function. 

If an instruction isn't in the instrumentation code, QBDI will try to use the ExecBroker to restore uninstrumented execution. The ExecBroker achieves this during function call, by remplacing the return address.

```python
def BranchLinkCB(vm, gpr, fpr, data):

    # get target address and current address
    # note : This work only if the callback is called in POSTINST position
    callAddress = gpr.pc
    currentAddress = vm.getInstAnalysis().address
    
    # TODO : test if we want to skip this call
    if data.testSkipBranch(callAddress):
        # If the target is ARM, we should exclude the aligned address to handle jump to thumb code
        alignedAddress = callAddress & ~1
        vm.removeInstrumentedRange(alignedAddress, alignedAddress + 4)
    
    return pyqbdi.CONTINUE

def run() :
    # skip : creation of the VM, allocation of the stack and other setup
    ....

    # register our callback on BL instruction
    vm.addMnemonicCB("BL", pyqbdi.POSTINST, BranchLinkCB, myData)

    # skip : run the VM as usual
    ....
```

**Comment by yujack008** [comment]
> We don't have an API that allow to easily skip the target of a call. However, you may achieved what you want with the [Instrumentation Ranges](https://qbdi.readthedocs.io/en/stable/api_description.html#instrumentation-ranges). This mechanism is usually used to avoid tracing call of another library (like libc). Although I do not recommend it, it is possible to use this mechanism to exclude the first instructions of a function.
> 
> If an instruction isn't in the instrumentation code, QBDI will try to use the ExecBroker to restore uninstrumented execution. The ExecBroker achieves this during function call, by remplacing the return address.
> 
> ```python
> def BranchLinkCB(vm, gpr, fpr, data):
> 
>     # get target address and current address
>     # note : This work only if the callback is called in POSTINST position
>     callAddress = gpr.pc
>     currentAddress = vm.getInstAnalysis().address
>     
>     # TODO : test if we want to skip this call
>     if data.testSkipBranch(callAddress):
>         # If the target is ARM, we should exclude the aligned address to handle jump to thumb code
>         alignedAddress = callAddress & ~1
>         vm.removeInstrumentedRange(alignedAddress, alignedAddress + 4)
>     
>     return pyqbdi.CONTINUE
> 
> def run():
>     # skip : creation of the VM, allocation of the stack and other setup
>     ....
> 
>     # register our callback on BL instruction
>     vm.addMnemonicCB("BL", pyqbdi.POSTINST, BranchLinkCB, myData)
> 
>     # skip : run the VM as usual
>     ....
> ```

very cool ,thank you very much.
