### ISSUE TITLE
How to write guest memory in QBDI?

### ISSUE THREAD

**Issue by rhino-li** [QBDI/QBDI#261]
**Bug description**
I am using [Triton](https://github.com/JonathanSalwan/Triton) to hook the '_xstat' function, attempting to synchronize the current context of the process to QBDI, allowing QBDI to execute, and then synchronizing the context back to Triton (similar to the cooperation between QBDI and Frida). 
My approach is to synchronize the register contents before using the pyqbdi.allocateVirtualStack()  to allocate virtual stack space. After that, I use the addMemAccessCB() to obtain memory block information when encountering memory READ, read the corresponding memory blocks from Triton's context, and write them into QBDI's context to ensure that instructions can read the desired memory. (Core codes will be posted later)
My problem is that when I try to use the writeMemory() method to write QBDI's memory, my script interrupted abnormally with the error message 'Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)'. How could I do this?

**Bug log**
```
__xstat hooked
[qbdi] Register rbx (qbdi: 0 != triton:200000000000000) synchronization
[qbdi] Register rcx (qbdi: 0 != triton:2) synchronization
[qbdi] Register rdx (qbdi: 0 != triton:9ffffffffffff20) synchronization
[qbdi] Register rdi (qbdi: 0 != triton:1) synchronization
[qbdi] Register rsi (qbdi: 0 != triton:200000000000000) synchronization
[qbdi] Register r12 (qbdi: 0 != triton:20000000000004c) synchronization
[qbdi] Register rsp (qbdi: 0 != triton:9fffffffffffef8) synchronization
[qbdi] Register rip (qbdi: 0 != triton:100000001e) synchronization
0x7f37333356c0: 	endbr64
0x7f37333356c4: 	mov	r8d, edi
0x7f37333356c7: 	mov	rdi, rsi
0x7f37333356ca: 	mov	rsi, rdx
0x7f37333356cd: 	cmp	r8d, 1
0x7f37333356d1: 	ja	45
0x7f37333356d3: 	mov	eax, 4
0x7f37333356d8: 	syscall
0x7f37333356da: 	cmp	rax, -4096
0x7f37333356e0: 	ja	6
sync memory 0x7f37333356e8: 	mov	rdx, qword ptr [rip + 911233]
sync memory by inst:0x7f37333356e8
qbdi_value : b'\x80\xff\xff\xff\xff\xff\xff\xff'
triton_value : b'\x00\x00\x00\x00\x00\x00\x00\x00'
[qbdi] Memory cells (0x7f3733413e70:8) synchronization

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```
**Minimal code to reproduce the bug**
Below is the core code of my script.
```
def initQBDI(so_name: string, api_name, ctx):
    lib = ctypes.cdll.LoadLibrary(so_name)
    api_ptr = ctypes.cast(getattr(lib, api_name), ctypes.c_void_p).value

    vm = pyqbdi.VM()
    gprState = vm.getGPRState()

    syncRegister_toQBDI(ctx, vm)

    vm.addInstrumentedModuleFromAddr(api_ptr)
    vm.recordMemoryAccess(pyqbdi.MEMORY_READ)
    vm.addMemAccessCB(pyqbdi.MemoryAccessType.MEMORY_READ, syncMemory_toQBDI, ctx) 
    vm.addCodeCB(pyqbdi.POSTINST, printInst, None)

    addr = pyqbdi.allocateVirtualStack(gprState, 0x100000)
    assert addr is not None

    pyqbdi.simulateCall(gprState, 0x42424242)
    vm.run(api_ptr, 0x42424242)

    syncRegister_toTriton(ctx, gprState)
    syncMemory_toTriton(vm, ctx)
    pyqbdi.alignedFree(addr)

    return

def syncMemory_toQBDI(vm, gpr, fpr, ctx):
    instruction = vm.getInstAnalysis()
    print("sync memory 0x{:x}: {}".format(instruction.address, instruction.disassembly))
    memory_access_list = vm.getInstMemoryAccess()
    for memory_access in memory_access_list:
        addr = memory_access.accessAddress
        size = memory_access.size
        print("sync memory by inst:{}".format(hex(memory_access.instAddress)))
        qbdi_value = pyqbdi.readMemory(addr, size)
        triton_value = ctx.getConcreteMemoryAreaValue(addr, size)
        print(qbdi_value)
        print(triton_value)

        if qbdi_value != triton_value:
            print(F"[qbdi] Memory cells ({hex(addr):s}:{size:d}) synchronization")
            FIX_MEMORY_CELLS[addr] = size
            pyqbdi.writeMemory(addr, triton_value)
    return pyqbdi.CONTINUE
```

**Version (please complete the following information):**
- OS:ubuntu20.04
- Architecture: X64
- QBDI version: 0.9.0
- Python version (for PyQBDI issue): 3.10

**Comment by nsurbay** [comment]
Hello,

The usage of ``writeMemory`` is the good function to write data in the current process. However, you can have the followed problem : 
- Does the region that you want to write is writable (ie, the instrumented code may attend to read ReadOnly memory) ?
- Do you load your library at the same address in QBDI and in Triton ? I expect that ``LoadLibrary`` (which would call ``dlopen``) may load your library at an arbitrary position at each execution (if ASLR is enabled). 

With your current code, I expect that you will have the followed issue : 
- With memory access using ``rip`` (like ``mov rdx, qword ptr [rip + 911233]``), the value that you read from Triton context may be nothing to do with you expect to read if you don't synchronised the position of the library between QBDI and Triton.
- If you load a shared library or executable (ie, a library that is linked with others library like the libc), you must not replace the value read from the GOT and the PLT. These tables hold value of others library method (like ``malloc`` function) and may not have the same value in Triton context.
- When you allocate the stack with ``allocateVirtualStack``, the register ``rsp`` will be changed. When the instrumented code will try to read the stack, the address returned by ``getInstMemoryAccess`` will not correspond to anything in Triton context, as the stack is at another address. Moreover, any pointer on the stack will also be different.
- How do you manage to synchronise the heap ? Usually, C code allocate memory using ``malloc``. However, by using PyQBDI, the heap is used by your instrumented code, by QBDI (to allocated internal object) and by python interpreter (to execute your script). It would be extremely unlikely that Triton ``malloc`` and the one use in the intrumented process returns the same address.
- The instrumented code can load and store pointer in memory (like when you implemented a liked list, each element store a pointer to the next one). If you have any difference between Triton and the instrumented process layout, how can you detect that the value read is a data (like the value of a linked element) or a pointer to another memory location (like the pointer to the next element) ? If you try to synchronized every read with the Triton context, you may replace pointer values.
- Finally, QBDI can only detect memory access that is perform by the instruction itself. However, It will not report indirect memory access. In your exemple, I see that the instruction ``syscall`` is instrumented. As the ``syscall`` instruction doesn't access userland memory, QBDI will report no memory access. However, depending of the syscall, the kernel may access and modify some memory. QBDI doesn't analyse syscall number and parameters to simulate memory access perform by the kernel.

**Comment by rhino-li** [comment]
Thank you very much for your timely response. 

My goal is to resolve the issue of Triton not being able to automatically emulate external library functions. After carefully considering what you said, I think my current approach might not be suitable. I don't know how to load the library to the same address in both QBDI and Triton. Regarding the heap, Triton allows control over the heap by overriding the `malloc()` method, but I don't know how to synchronize this with QBDI, and the issue with pointers is even more complex. Perhaps you have some insights? 

Thank you for your time.

**Comment by RobinDavid** [comment]
Hello @rhino-li.
I have been doing similar things in the past but I am not sure to understand.
You want to circumvent the fact that Triton does not support syscalls like xstats & co but you synchronize the triton state to the QBDI state.
QBDI will execute these calls, so its QBDI that is holding the truth. As such, I would synchronize the state the other way around, namely from QBDI to Triton.
Doing that way you can "recover" side-effect that have been missed by Triton.

On a side note, it will theoretically enable to catch up missed side-effect, but as you don't propagate symbolic side-effect you probably not be able to anything really relevant symbolically-wise.
In my experience you have no way but to model these syscalls. You can have a look at how we do it for very few of them in tritondse: https://github.com/quarkslab/tritondse/blob/main/tritondse/routines.py

**Comment by rhino-li** [comment]
Thank you for your response. @RobinDavid 
In the past couple of days, I have tried "from QBDI to Triton" and obtained some results that I expected. Currently, I am focusing on Triton's taint engine. Although the miss of symbolic side-effect is acceptable, it is undeniable that I still need to hook every external function.
I have been following your work on TritonDSE, it is impressive! Besides dynamic symbolic execution, it also addresses many detailed issues of Triton, such as heap management, which has been very helpful to me.

**Comment by nsurbay** [comment]
This issue seems to be solve. If not, feel free to reopen it.
