### ISSUE TITLE
Asserts are disabled in Debug builds

### ISSUE THREAD

**Issue by EliaGeretto** [QBDI/QBDI#48]
When building with `CMAKE_BUILD_TYPE=Debug`, asserts do not appear in the final build. It appears that a rogue `-DNDEBUG` makes it into the compilation commands.

**Comment by haxelion** [comment]
Yes indeed, this flag creeped in from blindly copying `llvm-config` output.

**Comment by EliaGeretto** [comment]
The same applies to the `-O3` compiler flag, which is also present when compiling with `CMAKE_BUILD_TYPE=Debug`.

**Comment by nezetic** [comment]
Fixed in 9300d9b. No need to enforce it as it's already handled by CMake. Closing.
