### ISSUE TITLE
CMake should export and install targets

### ISSUE THREAD

**Issue by EliaGeretto** [QBDI/QBDI#54]
Using a combination of `install(TARGETS ... EXPORT ...)` and `install(EXPORT ...`, CMake can generate a `QBDIConfig.cmake` file that will be installed and packaged together with the rest of the project.

This change is important since it will allow to refer to QBDI in projects that use it as a dependency just by importing its targets through `find_package(QBDI REQUIRED)` and then using `target_link_libraries` to link it when appropriate.

**Comment by nezetic** [comment]
I've pushed the modifications in commit 839b4070753e33cf9852de67586a1070360885e7.

I've renamed the CMake targets, to make them more coherent. As a consequence, it could break users' build scripts.

I propose to move those modification to milestone 0.7.

**Comment by nsurbay** [comment]
merge with x86 branch and release in 0.7.0
