### ISSUE TITLE
Drop pkg-config dependency

### ISSUE THREAD

**Issue by EliaGeretto** [QBDI/QBDI#55]
When #54 is fixed, it should be possible to modify the example projects to use `find_package` instead of `pkg-config` to import QBDI targets in CMake. This, in turn, should allow to drop the `pkg-config` package as a dependency on Linux systems.

The reason for this change is that, when considering Ubuntu, the `pkg-config` package has a large amount of dependencies on development tools that are not required to run QBDI, making the installation size increase considerably. As a side effect, the size of Docker images containing QBDI is more than double.

**Comment by nezetic** [comment]
Fix is available in a new branch [branch](/quarkslab/QBDI/tree/goodbye_pkgconfig), that replaces _pkg-config_ with _find_package_.
Modifications have been tested successfully on macOS, Linux and Windows, and greatly improve the way QBDI can be used using CMake.

Sadly, it also break projects linking using the old way. So I doubt it will be a good idea to merge this in 0.6.2.

**Comment by nsurbay** [comment]
merge with x86 branch and release in 0.7.0
