### ISSUE TITLE
Use Curses CMake module

### ISSUE THREAD

**Issue by EliaGeretto** [QBDI/QBDI#60]
The following code does not need to use the `PkgConfig` module; it should be sufficient to use the [`Curses` module](https://cmake.org/cmake/help/latest/module/FindCurses.html) provided by CMake, through `find_package` instead of `import`.
https://github.com/quarkslab/QBDI/blob/39a936b2efd000f0c5def0a8ea27538d7d5fab47/CMakeLists.txt#L178-L181
In addition, this should handle the `tinfo` dependency more gracefully, even if I did not test that.

It also looks like that this is the only place in which `pkg-config` is used during the build process, so this change should allow to drop it from the build dependencies.

**Comment by nezetic** [comment]
I tried to see if there was a workaround to avoid using pkg-config only to find if tinfo is needed.
Curses module is doing it already, without depending on pkg-config.
I've commited a new workaround based on that (commit 0a76f3f35b483d0fd5b9450d8877063b5fcb9856).

**Comment by nezetic** [comment]
I'm proposing to postpone this issue until 0.7, merging it with #55 and #54

**Comment by EliaGeretto** [comment]
I think you can simplify the patch even more using the `CURSES_LIBRARIES` variable that is set by the `Curses` module, as reported in the documentation I linked. That is supposed to handle the optional linking of `tinfo` on its own. So I would just put `CURSES_LIBRARIES` in `LLVM_LIBS` and keep the `find_package` statement.

**Comment by nezetic** [comment]
I was thinking to use `CURSES_LIBRARIES` indeed, but it's a list of the full paths for each library.
Previous CMake was using `LDFLAGS` output of `pkg-config`, that can be directly added to `LLVM_LIBS`, which contains the equivalent of `pkg-config --libs-only-l` for LLVM.
I looked at the `Curses` module, and there's no way to get the `LDFLAGS` for `ncurses`, so I used the current workaround.

**Comment by EliaGeretto** [comment]
I think that there is more than a list of paths in that variable, but I am not aware of the details. My previous comment was based on the fact that the following `CMakeLists.txt` works without any issues:
```
cmake_minimum_required(VERSION 3.2)
project(ncurses_test)

find_package(Curses REQUIRED)

add_executable(ncurses_test ncurses_test.c)

set(TEST_LIBS ${CURSES_LIBRARIES})
target_link_libraries(ncurses_test ${TEST_LIBS})
```
Then, from what I can see, `LLVM_LIBS` always ends up in a `target_link_libraries`, so the example above should prove that it works. I created the `TEST_LIBS` variable on purpose to simulate `LLVM_LIBS`.

**Comment by nezetic** [comment]
Yup, it works because you can pass a list of full paths to `target_link_libraries`.

In QBDI, `LLVM_LIBS` is also used to generate the `pkg-config` configuration file (`.pc`) file, that could be useful for some people and that I don't want to remove.

**Comment by EliaGeretto** [comment]
Ok, now I get it, it's because you want precisely `-lncurses` in the `.pc` file, understood.

**Comment by nsurbay** [comment]
merge with x86 branch and release in 0.7.0.

libncurses is a dependency of LLVM and may be remove in the future (see https://github.com/QBDI/QBDI/commit/2dc83f315070f188f26e4f4676480fa2f8d93a83)
