### ISSUE TITLE
Reduce size of Windows QBDI static library

### ISSUE THREAD

**Issue by nezetic** [QBDI/QBDI#70]
For a reason yet to be investigated, QBDI static library on Windows weighs more than 100 MB :(

It doesn't impact the size of binaries linked with it. But reducing the size of Windows QBDI static library could avoid wasting space.

**Comment by nsurbay** [comment]
With LLVM10, I rework the llvm libraries needed for QDBI. LLVMSelectionDag and LLVMCodeGen are no longer needed. Some others libraries are only needed for QBDITest and doesn't need to be include in QBDI_static.

In addition of reduce the compile time, the size of the windows static library is reduce to 25 Mo.
