### ISSUE TITLE
Missing R11 register

### ISSUE THREAD

**Issue by romainthomas** [QBDI/QBDI#78]
ARM ``R11`` is missing here: https://github.com/QBDI/QBDI/blob/c498ff22eb73600232610cca376c204da10af8e1/include/QBDI/State.h#L263-L265

**Comment by haxelion** [comment]
Depending on the convention, R11 is sometimes called FP. So it is present on the next LINE:
https://github.com/QBDI/QBDI/blob/c498ff22eb73600232610cca376c204da10af8e1/include/QBDI/State.h#L266

But you're not the only one asking that question so maybe it should be documented or at least added explained in comments ;-)
